### ISSUE TITLE
Document & Reduce Minimum Required Java Version

### ISSUE THREAD

**Issue by Valkryst** [openfga/java-sdk#108]
### Describe the problem you'd like to have solved

I'm currently evaluating a number of solutions (OpenFGA, Ory Keto, Permify, etc...) to be used in building a new permissions system for a large enterprise client.

As a part of the evaluation, I'm looking to ensure that the chosen solution has support for Java 8. The client is unable to update to a newer JDK, at least for now.

I didn't see the minimum required JDK version listed in the [readme](https://github.com/openfga/java-sdk/blob/main/README.md), or in the [release notes](https://github.com/openfga/java-sdk/releases). After looking through the Gradle-related files, it looks like the minimum required version is [Java 11](https://github.com/openfga/java-sdk/blob/0b7e643518793dd9c86efb5d7bef9086f553e42a/build.gradle#L29) and that it has been set to this since the [first commit](https://github.com/openfga/java-sdk/blob/647c77806c86380723648c82458583ec882d5d4c/build.gradle#L27).

### Describe the ideal solution

1. For the readme to be updated to include the minimum required Java version. A good spot may be near the line "It currently supports PostgreSQL 14 and MySQL 8.".
2. If possible, for the minimum required Java version to be set to Java 8.

**Comment by TomerPacific** [comment]
@rhamzeh = Can I help with this one?

**Comment by aaguiarz** [comment]
@TomerPacific I'm assigning it to you, thanks!

**Comment by TomerPacific** [comment]
@aaguiarz - Thanks, per @Valkryst's comment, should I just document the minimum supported version or also downgrade to Java 8 and see if everything works?
