### ISSUE TITLE
Unable to retrieve all tuples

### ISSUE THREAD

**Issue by duttkin** [openfga/java-sdk#30]
### Description

Unable to retrieve list of tuples using empty ClientReadRequest.  The read method always creates a TupleKey whether you pass in null or and empty ClientReadRequest.  This triggers a validation error when calling the api

I am attempting to simulate this request
curl --location --request POST 'http://localhost:8080/stores/<store id>/read'

### Version of SDK

> v0.2.1

### Version of OpenFGA (if known)

> v1.3.4

### OpenFGA Flags/Custom Configuration Applicable

>    environment:
      - OPENFGA_DATASTORE_ENGINE=mysql
      - OPENFGA_DATASTORE_URI=<user>:<pass>@tcp(mysql:3306)/fga?parseTime=true
      - OPENFGA_LOG_FORMAT=json

### Reproduction

The error occurs every time when attempting to read all tuples.  When you create an empty  ClientReadRequest with "new ClientReadRequest()" and call the read method, you will recieve the following error:
{
    "code": "validation_error",
    "message": "the 'tuple_key' field was provided but the object type field is required and both the object id and user cannot be empty"
}

### Sample Code the Produces Issues

ClientReadRequest request = new ClientReadRequest();
ClientReadOptions options = (new ClientReadOptions()).pageSize(10);
CompletableFuture future = client.read(request, options);

### Expected behavior
You should recieve a response listing the tuples on the server
The exact same behavior as "curl --location --request POST 'http://localhost:8080/stores/<store-id>/read'"

### Additional context

This issue is caused by the read method in the API.  It always creates a TupleKey and adds it to the body of the request even if the ClientReadRequest is empty.  It should leave the body empty and not create a TupleKey

**Comment by booniepepper** [comment]
Thanks for reporting, I'll look into it
