### ISSUE TITLE
A new thread is being created for every OpenFgaClient call

### ISSUE THREAD

**Issue by Jacksongoulart** [openfga/java-sdk#46]
### Description

A new HttpClient is being created for each request, leading to an increasing number of threads. Specifying a thread pool alleviates the problem, but not completely. The issue happens because [here](https://github.com/openfga/java-sdk/blob/2b4dec3bdbbf7d4f387ce06ce54357d0b19b7bc0/src/main/java/dev/openfga/sdk/api/client/ApiClient.java#L187) a new HttpClient is built everytime.

### Version of SDK

> v0.3.1

### Reproduction
Below is an example of how to reproduce the issue.

> 1. Initialize OpenFgaClient with any set of configs;
> 2. Invoke method OpenFgaClient#write(ClientWriteRequest request) multiple times;
> 3. Notice that for every write call, a new thread is created. If you have 300k write calls, 300k threads are created, eventually running out of memory.

### Expected behavior
> It should not create a new thread for every request.

**Comment by jimmyjames** [comment]
Thanks for reporting, you are correct; we should not create a new http client for each request.

**Comment by rhamzeh** [comment]
Thanks for the keen eye @Jacksongoulart 🕵🏽 

The fix is now out in [v0.3.2](https://github.com/openfga/java-sdk/releases/tag/v0.3.2)
