### ISSUE TITLE
OAuth2 client credentials are sent with wrong Content-Type

### ISSUE THREAD

**Issue by nverbos-godaddy** [openfga/java-sdk#47]
### Description

When an OAuth2 access token is requested from an OAuth2 Authorization server's token endpoint, the credentials are sent using the `application/json` Content-Type, but client credentials should be sent using the `application/x-www-form-urlencoded` [according to the OAuth 2.0 RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1)

### Version of SDK
v0.3.1

### Reproduction
1. Configure the openfga client using the [OAuth2 Credentials example in the README](https://github.com/openfga/java-sdk?tab=readme-ov-file#oauth2-credentials)
2. Observe that the content-type is set to `application/json`

### Expected behavior
When an OAuth2 token is requested from an OAuth2 Authorization server, the credentials are sent using the `application/x-www-form-urlencoded` content-type [as specified in the OAuth 2.0 RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1)

**Comment by rhamzeh** [comment]
Thanks for the report @nverbos-godaddy!

**Comment by rhamzeh** [comment]
@le-yams just looping you in as you had contributed that code. Would changing the content type still work for you?

**Comment by le-yams** [comment]
> @le-yams just looping you in as you had contributed that code. Would changing the content type still work for you?

Absolutely, @nverbos-godaddy is right 😄

**Comment by le-yams** [comment]
@rhamzeh I've created [a PR in the sdk-generator](https://github.com/openfga/sdk-generator/pull/281) project to fix this.

**Comment by rhamzeh** [comment]
Thank you!

**Comment by rhamzeh** [comment]
Thanks for the report @nverbos-godaddy and for your help @le-yams !

This should be out in the just released [v0.3.2](https://github.com/openfga/java-sdk/releases/tag/v0.3.2)
