### ISSUE TITLE
Allow specifying OAuth Token URL in ClientCredentials

### ISSUE THREAD

**Issue by hkarn-godaddy** [openfga/java-sdk#66]
### Describe the problem you'd like to have solved

You can specify `apiTokenIssuer` in [ClientCredentials](https://github.com/openfga/java-sdk/blob/main/src/main/java/dev/openfga/sdk/api/configuration/ClientCredentials.java) but the token path always defaults to ["/oauth/token"](https://github.com/openfga/java-sdk/blob/main/src/main/java/dev/openfga/sdk/api/auth/OAuth2Client.java#L25C65-L25C79). That may not always be true as for me it's `/oauth2/token`.

I need to create a separate OAuth client and manage token manually.

### Describe the ideal solution

Replace or add a new field in [ClientCredentials](https://github.com/openfga/java-sdk/blob/main/src/main/java/dev/openfga/sdk/api/configuration/ClientCredentials.java) to accept apiTokenURL (the entire path) or optionally add a field to allow overriding `DEFAULT_API_TOKEN_ISSUER_PATH` in `OAuth2Client`.

## Alternatives and current workarounds

Create a separate OAuth client and manage token manually.

### Additional context

None.

**Comment by rhamzeh** [comment]
Hi @hkarn-godaddy - what version of the SDK are you using?

This should be already possible as of v0.3.0 thanks to this PR by @le-yams https://github.com/openfga/sdk-generator/pull/240

You can set the API Token Issuer as follows:

| `ApiTokenIssuer` | Endpoint SDK will hit |
| --- | --- |
| `issuer.fga.example` |  `https://issuer.fga.example/oauth/token` |
| `https://issuer.fga.example` |  `https://issuer.fga.example/oauth/token` |
| `https://issuer.fga.example:8080` |  `https://issuer.fga.example:8080/oauth/token` |
| `issuer.fga.example/some_endpoint` |  `https://issuer.fga.example/some_endpoint` |
| `https://issuer.fga.example/some_endpoint` |  `https://issuer.fga.example/some_endpoint` |
| `https://issuer.fga.example:8080/some_endpoint` |  `https://issuer.fga.example:8080/some_endpoint` |

**Comment by hkarn-godaddy** [comment]
Sorry. You are right. This already works in the new version. Closing request.
